### ISSUE TITLE
Improvements and additional features

### ISSUE THREAD

**Issue by agatatalita** [ditup/ditapi#38]
- [ ]  being able to choose the tag from tags page and easily add it to "my tags", also from other user's tags.
 Could be popup with options: see tag page, add to my tags.
As a first step, there could be "add to my tags" option on tag's page.
- [ ] direct easily accessible link to "my contacts" - maybe in "people" but I would expect it more in the menu on the right - personal menu, now it is not so easy to access
- [ ] notification about new contact requests should be done like in messages, could be over the link to the "my contacts" page
- [ ] reference for the user could be shown somewhere on the contact page. Possibly in smaller text next to picture or in some popup with contact.
- [ ] feedback functionality
- [ ] some help explaining e.g. colors of signs next to peoples contact pictures
- [ ] if there will be ever an issue with too many loaded messaged at once, it would be nice to solve it with navigating with pages (not scrolling up and loading more),

**Comment by mrkvon** [comment]
moved to ditup/ditapp#21
